name: ynov_immo
description: A new Flutter project.

version: 1.0.0+1

environment:
  sdk: ">=2.2.2 <3.0.0"

dependencies:
  carousel_slider: ^4.0.0
  http: '^0.12.0'
  autocomplete_textfield: ^1.6.4
  flutter_typeahead: ^3.1.3
  google_maps_flutter: ^2.0.11
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.0
  flutter_svg: ^0.20.0-nullsafety.3
  smooth_star_rating: ^1.0.4
  flutter_map: any
  flutter_map_marker_popup: ^0.1.4

dev_dependencies:
  build_runner: ^1.5.0
  pedantic: ^1.7.0
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - assets/icons/

